# Generated by Django 4.2 on 2023-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True)),
                ('pos_start', models.IntegerField(blank=True)),
                ('pos_end', models.IntegerField(blank=True)),
                ('content', models.TextField(max_length=20000)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='chat',
            name='gpt',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
