# Generated by Django 4.2 on 2023-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBackend', '0003_rename_content_operation_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='operation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
